Uprev the base image from trusty to bionic
lsst-sqre/lsst-texlive pull request #2
Opened 2019-09-30 23:25 UTC by SimonKrughoff

This image only makes Python 3.4.3 available, but some of the new documentation tooling uses f-strings.  These require Python 3.7 to function.  I'm suggesting just upping the base image.  I have not tested whether package names have changed in  the interim, but I hope they have not.

2019-09-30 23:27 UTC, SimonKrughoff commented
OK.  So travis failed not being able to find a package name.  This will require a little more looking.

2019-09-30 23:47 UTC, SimonKrughoff commented
It seems like the only offending package is `latex-xcolor`.

2019-10-01 16:26 UTC, SimonKrughoff commented
Travis has passed.  I think this is now ok to merge, but I don't know if I should do more complete testing.

2019-10-01 18:08 UTC, jonathansick requested changes
Please squash the last two commits.

Once this is merged to master it’ll build a new `latest` docker image from Travis and get used from lsst-texmf.

Note that in order for the change to be useful you’ll need to install third party dependencies required by db2author.py in the lsst-texmf image.

2019-10-01 18:30 UTC, SimonKrughoff commented
Rebased.  I am doing the changes to `lsst-texmf` on a different PR [here](https://github.com/lsst/lsst-texmf/pull/196).

2019-10-01 18:41 UTC, jonathansick approved these changes

2019-10-01 18:43 UTC, merged